name: easymedpro
description: EasyMedPro Flutter app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

flutter:
  uses-material-design: true
