name: flutter_voice_assistant
description: Voice assistant module for EasyMedPro using speech_to_text and flutter_tts.
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.5.0
  flutter_tts: ^3.6.3
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
