name: Deploy EasyMedPro to Firebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
  VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
  VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
  VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
  VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
  VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
  VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run lint
      run: npm run lint

    - name: Build Project
      run: npm run build

    - name: Setup Java (for Android build)
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
      if: github.ref == 'refs/heads/main'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      if: github.ref == 'refs/heads/main'

    - name: Sync Capacitor
      run: npx cap sync
      if: github.ref == 'refs/heads/main'

    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleDebug
      if: github.ref == 'refs/heads/main'

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EASYMED_8C074 }}'
        projectId: easymed-8c074
        channelId: live
      if: github.ref == 'refs/heads/main'

    - name: Deploy to Firebase Hosting (Preview)
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EASYMED_8C074 }}'
        projectId: easymed-8c074
      if: github.event_name == 'pull_request'

    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: easymedpro-android-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
      if: github.ref == 'refs/heads/main'

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          ## Changes in this Release
          - Web app deployed to Firebase Hosting
          - Android APK available for download
          - Progressive Web App with offline functionality
          
          ## Downloads
          - Web App: https://easymed-8c074.web.app
          - Android APK: See assets below
        draft: false
        prerelease: false
      if: github.ref == 'refs/heads/main'